config/routes.rb
TasksApp::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  resources :users
  resources :tasks do
     resources :comments, controller: 'tasks/comments'
  end

  resources :notifications do
    collection do
      get 'contextual_menu'
    end
  end

  namespace :admin do
    resources :users
    resources :user_roles
    resources :task_categories
    resources :tasks
  end

  match 'admin/tasks/search' => 'admin/tasks#search', :as => :admin_tasks_search, via: [:post]
  match 'admin/users/:id/activation' => 'admin/users#activation', :as => :activation_admin_user, via: [:put]
  match 'admin/users/:id/permissions' => 'admin/user_roles#permissions', :as => :permissions_admin_user_roles, via: [:put]

  root to: 'home#index'

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  task_name   :string(255)
#  start_date  :date
#  due_date    :date
#  category_id :integer
#  status_id   :integer
#  author_id   :integer
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Task < ActiveRecord::Base
  attr_accessible :author_id, :category_id, :description, :due_date, :start_date, :status_id, :task_name

  belongs_to :category, class_name: 'TaskCategory', foreign_key: "category_id"

  belongs_to :author, class_name: 'User', foreign_key: "author_id"

  belongs_to :status, class_name: 'TaskStatus', foreign_key:"status_id"

  has_many :assignations, dependent: :destroy
  has_many :users_assigned, through: :assignations, source: :user
  accepts_nested_attributes_for :users_assigned

  has_many :comments, dependent: :destroy


  validates :task_name, presence: true, length: { maximum: 50 }
  validates :due_date, presence: true
  # validates :category_id, presence: true
  validates :author_id, presence: true
  # validates :description, presence: true

  default_scope order: 'tasks.due_date ASC'


  scope :author_id, ->(value) { where(author_id: value) }
  scope :category_id, ->(value) { where(category_id: value) }
  scope :status_id, ->(value) { where(status_id: value) }

end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :role_admin?


  def index
   @tasks = Task.all

   if params[:sort_param]=="created_date"
     @tasks = @tasks.sort_by{|e| e[:created_at]}.reverse
   elsif params[:sort_param]=="due_date"
     @tasks = @tasks.sort_by{|e| e[:due_date]}
   end

  end


  def search
# redirect_to admin_tasks_path(params[:task])

    @tasks = Task.scoped
    @tasks = @tasks.author_id(params[:task][:author_id]) if params[:task][:author_id].present?
    @tasks = @tasks.category_id(params[:task][:category_id]) if params[:task][:category_id].present?
    @tasks = @tasks.status_id(params[:task][:status_id]) if params[:task][:status_id].present?

    @u_t = User.find(params[:user_assigned_id]).tasks_assigned if params[:user_assigned_id].present?

    if(!@u_t.nil?)
      @tasks = @tasks & @u_t
    end

    respond_to do |format|
      format.html { render :index, :locals => {tasks: @tasks} }
      format.json
      format.js
    end
  end


end

app/controllers/tasks/comments_controller.rb
class Tasks::CommentsController < ApplicationController
  def create
  @task = Task.find(params[:task_id])
  params[:comment][:user_id] = current_user.id


  @task.comments.create(params[:comment])

  respond_to do |format|
    format.html
    format.json
    format.js
  end


  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_edit_permission, only: [:edit, :update]

  def index
    @tasks_assigned = current_user.tasks_assigned
    @tasks_created = current_user.tasks_as_author

    @tasks = @tasks_assigned
    if params[:filter] == "authored"
       @tasks = @tasks_created
    end

  end


  def new
    @users = User.active
    @task_categories = TaskCategory.all
  end


  def create
    due_date = date_from_form(params[:due_dt])
    params[:task][:due_date]= due_date
    start_date = date_from_form(params[:start_dt])
    params[:task][:start_date] = start_date

    params[:task][:status_id] = TaskStatus.find_by_status("Created").id

    @task = current_user.tasks_as_author.build(params[:task])

    if @task.save
      params[:users_assigned][:user_id].each { |u_id|
        Assignation.create(task_id: @task.id, user_id: u_id) if !u_id.blank?
      }
      flash[:notice] = "Task created!"
      redirect_to(tasks_path(filter:"authored"))
    else
      flash[:alert] = "Task was not created"
      redirect_to(new_task_path)
    end

  end


  def show
    @task= Task.find(params[:id])
    @author = Task.find(params[:id]).author
   # @comments = @task.comments
  end


  def edit
    @task= Task.find(params[:id])

    @users = User.active
    @task_categories = TaskCategory.all
    @task_statuses = TaskStatus.all

    @users_assigned_ids = @task.users_assigned.pluck(:id)
  end


  def update


   @task= Task.find(params[:id])

   due_date = date_from_form(params[:due_dt])
   params[:task][:due_date] = due_date
   start_date = date_from_form(params[:start_dt])
   params[:task][:start_date] = start_date

   # Checks if some mandatory parameters are empty or nil
   if params[:task][:task_name] == "" || params[:task][:due_date] == nil
     flash[:alert] = "Task was not updated"
     redirect_to(task_path(@task))
     return
   end


    if @task.update_attributes(params[:task])
      # Delete assignations for which their user_id does not match a user_id in params[:users_assigned]
      assignations = Assignation.where(task_id:@task.id)
      assignations.pluck(:user_id).each { |a|
          unless params[:users_assigned].include?(a.to_s)
           assignation_id = Assignation.where(task_id: @task.id, user_id: a).pluck(:id)
           Assignation.destroy(assignation_id)
          end
      }

      # Create assignations that were added to the form
      if params[:users_assigned].present?
        params[:users_assigned].each { |u_id|
          if !u_id.blank? && Assignation.where(task_id: @task.id, user_id: u_id).empty?
            Assignation.create(task_id: @task.id, user_id: u_id)
          end
        }
      end

      flash[:notice] = "Task updated"
      redirect_to(task_path(@task))
    else
      flash[:alert] = "Task was not updated"
      render 'edit'
    end

  end


  private

  def require_edit_permission
    if current_user != Task.find(params[:id]).author && !current_user.admin?
      redirect_to(tasks_path(filter:"authored"))
    end
  end


end

app/views/tasks/_comment_form.html.erb
<h4>
  Comment &nbsp <span class="glyphicon glyphicon-comment"></span>
</h4>

<div class="row">
  <div class="span6 offset3">
    <%= form_for Comment.new, url: task_comments_path(@task), remote: true do |f| %>

        <%= f.text_area :text, class:"form-control", cols: "30", rows: "5" %>
        </br>
        <div class="text-right">
          <%= f.submit "Post", class: "btn btn-large btn-primary" %>
        </div>

        <% end %>
  </div>
</div>

app/views/tasks/_comments.html.erb
<h4>User Comments </h4>
</br>

<% if @task.comments.any? %>

  <% @task.comments.each do |c| %>
    <div class="panel panel-info">
      <div class="panel-heading">
        <h6 class="panel-title">
          <%=   c.user.name  %> -  <%=   c.user.email  %>
          <span class="pull-right">
            <%=   c.created_at %>
          </span>
        </h6>
      </div>
      <div class="panel-body">
        <%=   c.text %>
      </div>
    </div>
  <% end %>

<% else %>
  No comment on this task yet

<% end %>

app/views/tasks/edit.html.erb
<h2>Task: <%=  @task.task_name %></h2>

<%= form_for(@task)  do |f|  %>
    <div class="form-group">
      <%= f.label :task_name, "Task Name" %>
      <%= f.text_field :task_name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class:"form-control", cols: "30", rows: "7" %>
    </div>
    <div class="form-group">
      <%= f.label :users_assigned, "User Assigned to this Task" %><br>
      <%= select_tag :users_assigned,
                     options_for_select(@users.collect {|x| [x.name, x.id]}, selected: @users_assigned_ids), include_blank: true, multiple: true
      %>
    </div>
    <div class="form-group">
      <%= f.label :category_id, "Task Category" %><br>
      <%= f.collection_select :category_id, TaskCategory.all, :id, :category, {include_blank: true}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :start_dt, "Start Date (optional)" %>
      <% start_dt = @task.start_date  %>
      <%= select_date(start_dt, selected: @task.start_date, prefix: :start_dt, include_blank: true, start_year: Time.now.year)  %>
    </div>

    <div class="form-group">
      <%= f.label :due_dt, "Due Date" %>
      <% due_dt = @task.due_date  %>
      <%= select_date(due_dt, selected: @task.due_date, prefix: :due_dt, include_blank: true, start_year: Time.now.year)  %>
    </div>

    <div class="form-group">
      <%= f.label :status_id, "Status" %>
      <%= f.collection_select :status_id, @task_statuses, :id, :status, include_blank: true %>
    </div>
<%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/tasks/index.html.erb
<ul class="nav nav-tabs pull-right">
  <li role="presentation" >
    <%= link_to "Tasks Assigned",  tasks_path(filter:"assigned") %>
  </li>
  <li role="presentation" >
    <%= link_to "Tasks Authored",  tasks_path(filter:"authored")%>
  </li>
</ul>
</br>


<h2><%= t("filter_titles.#{params[:filter]}") %></h2>


Number of tasks: <%= @tasks.count %>
</br></br>


Task assigned
<%= render partial: 'shared/tasks_table', :locals => { :tasks => @tasks}%>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= form_for(Task.new, :url => { :action => "create" })  do |f| %>
    <div class="form-group">
      <%= f.label :task_name, "Task Name (*)" %>
      <%= f.text_field :task_name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class:"form-control", cols: "30", rows: "7" %>
    </div>
    <div class="form-group">
      <%= fields_for :users_assigned do |users_assigned_form| %>
          <%= users_assigned_form.label :user_id, "User Assigned to this Task" %><br>
          <%= users_assigned_form.select :user_id, @users.collect {|x| [x.name, x.id]}, {include_blank: true}, :multiple => true, class:"form-control" %>

      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :category_id, "Task Category" %><br>
      <%= f.collection_select :category_id, TaskCategory.all, :id, :category, {include_blank: true}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :start_dt, "Start Date (optional)" %>
      <%= select_date nil, :prefix => :start_dt, :include_blank => true, class:"form-control", start_year: Time.now.year  %>
    </div>

    <div class="form-group">
      <%= f.label :due_dt, "Due Date (*)" %>
      <%= select_date nil, :prefix => :due_dt, :include_blank => true, class:"form-control", start_year: Time.now.year %>
    </div>
<%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/tasks/show.html.erb
<h2>Task: <%=  @task.task_name %>
  <% if @task.status.present? %>
    <span class="badge badge-light"><%= @task.status.status %></span>
  <% end %>


  <% if @author == current_user || current_user.admin? %>
    <%= link_to  edit_task_path(@task), class:"pull-right" do %>
      <span class="glyphicon glyphicon-edit" alt="edit"></span>
    <% end %>
  <% end %>
</h2>

</br>



<div class="">
  <div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">
    </div>

    <!-- List group -->
    <ul class="list-group">
      <li class="list-group-item">Created by: &nbsp&nbsp <%=  @task.author.name %> (<%=  @task.author.email %>) </li>
      <li class="list-group-item">    Category: &nbsp&nbsp
        <%= if @task.category.present?
              @task.category.category
            end
        %>
      </li>
      <li class="list-group-item">Description: &nbsp&nbsp <%=     @task.description  %></li>
      <li class="list-group-item"> Assigned to: &nbsp&nbsp
        <% @task.users_assigned.each do |u| %>
          <%=   u.name %>
          (<%=   u.email %>)
        <% end %>
      </li>
      <li class="list-group-item">Start Date: &nbsp&nbsp <%=     @task.start_date.to_s  %></li>
      <li class="list-group-item">DUE DATE: &nbsp&nbsp <%=     @task.due_date.to_s  %></li>
      <li class="list-group-item">
        Status: &nbsp&nbsp
        <%= if @task.status.present?
              @task.status.status
            end
        %>
      </li>

    </ul>


    <div class="panel-body">

    </div>


  </div>


  </br></br>

  <%= render :partial => 'comment_form', :locals => { :task_id => @task.id, :user_id => current_user.id }  %>
  </br>
  <div class="comments"> <%= render :partial => 'tasks/comments' %> </div>


</div>