config/routes.rb
TasksApp::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  resources :users
  resources :tasks do
     resources :comments, controller: 'tasks/comments'
  end

  resources :notifications do
    collection do
      get 'contextual_menu'
    end
  end

  namespace :admin do
    resources :users
    resources :user_roles
    resources :task_categories
    resources :tasks
  end

  match 'admin/tasks/search' => 'admin/tasks#search', :as => :admin_tasks_search, via: [:post]
  match 'admin/users/:id/activation' => 'admin/users#activation', :as => :activation_admin_user, via: [:put]
  match 'admin/users/:id/permissions' => 'admin/user_roles#permissions', :as => :permissions_admin_user_roles, via: [:put]

  root to: 'home#index'

end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  description :string(255)
#  read        :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Notification < ActiveRecord::Base
  attr_accessible :description, :read, :user_id

  belongs_to :user

  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 200 }
  # validates :read, presence: true

  default_scope order: 'notifications.created_at DESC'


  def self.unread
    where(read: false)
  end


end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @notifications = current_user.notifications

    # @notifications.pluck(:id).each do |n_id|
    #   Notification.find(n_id).update_attributes(read: true)
    # end

  end


  def destroy
    Notification.find(params[:id]).destroy
    redirect_to notifications_url
  end



  def edit #mark as read
    Notification.find(params[:id]).update_attributes(read: true)
    redirect_to(notifications_path)
  end

end

app/views/notifications/_unread_notifications.html.erb
<!-- The Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">
          <span class="glyphicon glyphicon-bell"></span> New Notifications (<%=current_user.notifications.unread.count %>)
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </h4>
      </div>

      <!-- Modal body -->
      <div class="modal-body">

          <% if current_user.notifications.unread.any? %>
              <% current_user.notifications.unread.each do |notification| %>
                <div class="list-group">
                <%= link_to edit_notification_path(notification), class:"list-group-item list-group-item-action flex-column align-items-start active" do %>
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">  <%= notification.description %>   </h5>
                  <small>  <%= time_ago_in_words(notification.created_at) %> ago   </small>
                </div>
                <p class="mb-1"></p>
                <small></small>
                <% end %>
                </div>
              <% end %>

          <% end %>

      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <!--<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>-->
        <% #submit_tag 'Close', :type => :reset, :class => "btn btn-dark", "data-dismiss" => "modal", "aria-hidden" => "true" %>
        <button type="button" class="btn btn-default">
          <%= link_to "See All", notifications_path %>
        </button>
      </div>

    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<h2>Notifications</h2>
<% if current_user.notifications.any? %>

  <table class="table table-hover">
    <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @notifications.each do |n| %>
      <tr>
        <td>
          <a href="<%= edit_notification_path(n) %>" class="list-group-item list-group-item-action <%= 'active' unless n.read %>">
            <span class="content"><%= n.description %></span>
            <span class="timestamp">
            <%= time_ago_in_words(n.created_at) %> ago.
            </span>
          </a>
        </td>
        <td>
          <%= link_to n, method: :delete, data: { confirm: "Are you sure?" } do %>
            <span class="glyphicon glyphicon-remove" alt="delete"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

<% end %>