config/routes.rb
TasksApp::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  resources :users
  resources :tasks do
     resources :comments, controller: 'tasks/comments'
  end

  resources :notifications do
    collection do
      get 'contextual_menu'
    end
  end

  namespace :admin do
    resources :users
    resources :user_roles
    resources :task_categories
    resources :tasks
  end

  match 'admin/tasks/search' => 'admin/tasks#search', :as => :admin_tasks_search, via: [:post]
  match 'admin/users/:id/activation' => 'admin/users#activation', :as => :activation_admin_user, via: [:put]
  match 'admin/users/:id/permissions' => 'admin/user_roles#permissions', :as => :permissions_admin_user_roles, via: [:put]

  root to: 'home#index'

end

app/views/shared/_flash_messages.html.haml
#flash_messages
 - if flash[:notice]
  .alert.alert-success{:role => "alert"}
   = notice

 - if flash[:alert]
  .alert.alert-danger{:role => "alert"}
   = alert

app/views/shared/_tasks_table.html.erb
<div class="tasks">
  <table class="table table-hover">
    <thead>
    <tr>
      <th scope="col">Task ID</th>
      <th scope="col">Title</th>
      <th scope="col">Due Date</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% tasks.each do |t| %>
      <tr>
        <th scope="row"> <%=   t.id %> </th>
        <td> <%=   t.task_name %> </td>
        <td> <%=   t.due_date %> </td>
        <td>
          <%= link_to  task_path(t) do %>
            <span class="glyphicon glyphicon-eye-open" alt="show"></span>
          <% end %>
        </td>
        <td>
          <% if t.author == current_user || current_user.admin? %>
            <%= link_to  edit_task_path(t) do %>
              <span class="glyphicon glyphicon-edit" alt="edit"></span>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>