config/routes.rb
TasksApp::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :user do
    resource :registration,
             only: [:new, :create, :edit, :update],
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration do
      get :cancel
    end
  end

  resources :users
  resources :tasks do
     resources :comments, controller: 'tasks/comments'
  end

  resources :notifications do
    collection do
      get 'contextual_menu'
    end
  end

  namespace :admin do
    resources :users
    resources :user_roles
    resources :task_categories
    resources :tasks
  end

  match 'admin/tasks/search' => 'admin/tasks#search', :as => :admin_tasks_search, via: [:post]
  match 'admin/users/:id/activation' => 'admin/users#activation', :as => :activation_admin_user, via: [:put]
  match 'admin/users/:id/permissions' => 'admin/user_roles#permissions', :as => :permissions_admin_user_roles, via: [:put]

  root to: 'home#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  name                   :string(255)
#  active                 :boolean          default(TRUE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :title, :body

  attr_accessible :email, :name, :active

  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles

  has_many :tasks_as_author, class_name: "Task", foreign_key: :author_id

  has_many :assignations, dependent: :destroy
  has_many :tasks_assigned, through: :assignations, source: :task

  has_many :comments

  has_many :notifications, dependent: :destroy


  # after_create :add_default_role


  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  default_scope order: 'users.name ASC'

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

  def self.active
    where(active: true)
  end

  def admin?
    @admin_role = Role.admin_role
    self.roles.exists?(@admin_role)
  end



  # def regular?
  #   @regular_role = Role.regular_role
  #   self.roles.exists?(@regular_role)
  # end



  private

  # def add_default_role
  #   @regular_role_id = Role.regular_role.id
  #   UserRole.create(user_id: self.id, role_id: @regular_role_id)
  # end




end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :role_admin?


  def index
    @users = User.all
  end


  def show
    @user = User.find(params[:id])
  end


  def new
  end


  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "User created!"
      redirect_to(admin_users_path)
    else
      flash[:alert] = "User not created"  #@user.errors
      render 'new'
    end
  end


  def edit
    @user = User.find(params[:id])
    @user_roles_ids = @user.roles.pluck(:role_id)

    if @user.active
      @panel_title = "Deactivate account"
      @btn_text = "Set Inactive"
    else
      @panel_title = "Activate account"
      @btn_text = "Set Active"
    end
  end


  def update
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])

      flash[:notice] = "Profile updated"
      redirect_to(admin_user_path(@user))
    else
      flash[:alert] = "User profile not updated"
      redirect_to(admin_user_path(@user))
    end

  end


  def destroy
    @user = User.find(params[:id])
    # if User.find(params[:id]).destroy
    #   flash[:notice] = "User deleted"
    #   redirect_to(admin_users_path)
    # elsif
    #   flash[:alert] = "User not deleted"
    #   redirect_to(admin_user_path(@user))
    # end
  end

  def activation
    @user = User.find(params[:id])

    if @user.active
      message = "deactivation"
      @user.password = Devise.friendly_token.first(8) #generated password
    else
      message = "activation"
    end

    @user.toggle(:active)

    if @user.save
      flash[:notice] = "User "+message+" successful"
    elsif
      flash[:alert] = "User "+message+" unsuccessful"
    end

    redirect_to admin_user_path(@user)
  end




  private

  def current_user?(user)
    user == current_user
  end



end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]


  skip_before_filter :require_no_authentication, only: [:new]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :authenticate_user!, only: [:index]
  before_filter :correct_user, only: [:show, :edit, :update]


  def show

  end

  def edit
   @user = User.find(params[:id])
   redirect_to(edit_user_registration_path)
  end

  def update

  end


  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user) || current_user.admin?
  end

  def current_user?(user)
    user == current_user
  end



end

app/views/admin/users/edit.html.erb
<h2>
  <%= @user.name %>

  <% if !@user.active %>
    <small><span class="label label-default">Inactive</span></small>
  <% end %>
</h2>

<div class="row">
  <% if @user.active %>
    <div class="col-sm-6 mb-3 mb-md-0">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Update Account</h3>
        </div>
        <div class="panel-body">
          <%= form_for(@user, url: admin_user_path(@user), html: { method: :put }) do |f| %>


            <div class="field">
              <%= f.label :name %> <br />
              <%= f.text_field :name %>
            </div>

            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true %>
            </div>



            <div class="field">
              <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
              <%= f.password_field :password, autocomplete: "off" %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off" %>
            </div>

            <div class="actions text-right">
              <%= f.submit "Update", class:"btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>

    </div>

  <% else %>

  <% end %>


  <div class="col-sm-6">

    <% if @user.active %>

      <div class="panel panel-warning">

        <div class="panel-heading">
          <h3 class="panel-title">User Roles</h3>
        </div>

        <div class="panel-body">
          <%= form_for(@user, url:  permissions_admin_user_roles_path, html: { method: :put }) do |form| %>

            <div class="field">
              <%= form.label :user_roles, "User Roles" %><br>
              <%= select_tag :user_roles,
                             options_for_select(Role.all.collect {|x| [x.role_name, x.id]}, selected: @user_roles_ids),
                             multiple: true, include_blank: true
              %>

            </div>

            <div class="actions">
              <%= form.submit "Change Permissions", class:"btn btn-warning" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

      <div class="panel panel-danger">

        <div class="panel-heading">
          <h3 class="panel-title"><%= @panel_title %></h3>
        </div>

        <div class="panel-body">
          <% if @user != current_user %>
            <%= button_to @btn_text, activation_admin_user_path(@user), data: { confirm: "Are you sure?" }, method: :put, class: 'btn btn-danger' %>
          <% else %>
            This action is not permitted on your own account
          <% end %>
        </div>
     </div>

    </div>


<!--    <div class="panel panel-danger">-->
<!--      <div class="panel-heading">-->
<!--        <h3 class="panel-title">Delete</h3>-->
<!--      </div>-->

<!--      <div class="panel-body">-->
        <%# button_to "Delete account", admin_user_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %>
<!--      </div>-->
<!--    </div>-->


  </div>

</div>

<% # link_to "Back", :back %>

app/views/admin/users/index.html.erb
<h2>
  Users
  <%= button_to "+ New User", new_admin_user_path, method: :get, class: 'btn btn-primary pull-right' %>
</h2>
Number of users: <%= @users.count%>


<br></br>


<table class="table table-hover">
  <thead>
  <tr>
    <th scope="col">ID (#)</th>
    <th scope="col">Name</th>
    <th scope="col">Email</th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |u| %>
      <tr>
        <th scope="row"> <%=   u.id %> </th>
        <td>
          <%=   u.name %>
          <% unless u.active %>
            <span class="label label-default">Inactive</span>
          <% end %>
        </td>
        <td> <%=   u.email %> </td>
        <td>
        </td>
        <td>
          <%= link_to  admin_user_path(u) do %>
              <span class="glyphicon glyphicon-eye-open" alt="show"></span>
          <% end %>
        </td>
        <td>
          <%= link_to  edit_admin_user_path(u) do %>
              <span class="glyphicon glyphicon-edit" alt="edit"></span>
          <% end %>
        </td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/admin/users/new.html.erb
<h2>New User</h2>

<%= form_for(User.new, :url => { :action => "create" }) do |f| %>


    <div class="form-group">
    <%= f.label :name %> <br />
      <%= f.text_field :name, class: "form-control" %>
    </div>

  <div class="form-grouop">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
  </div>


  <div class="actions">
    <%= f.submit "Save", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<div class="">
  <section>

    <h2>
      <%= @user.name %>

      <%= link_to  edit_admin_user_path(@user), class:"pull-right" do %>
        <span class="glyphicon glyphicon-edit" alt="edit"></span>
      <% end %>

      <% if @user.active %>

      <% else %>
        <small><span class="label label-default">Inactive</span></small>
      <% end %>

      </br>
      <small>User #<%= @user.id %></small>
    </h2>


  </section>

</div>

</br></br>

  <section>

    <table class="table table-sm">
      <thead>
      <tr>
        <th>
          <% @user.roles.each do |ur| %>
              <%=   ur.role_name %> &nbsp
          <% end %>
        </th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>  Email address :</td>
        <td> <%= @user.email %> </td>
        <td></td>
      </tr>
      <tr>
        <td>  Last signed in :</td>
        <td> <%= @user.last_sign_in_at %> </td>
        <td></td>
      </tr>
      <tr>
        <td>User created :</td>
        <td><%= @user.created_at %></td>
        <td></td>
      </tr>
      <tr>
        <td>Last account update : </td>
        <td><%= @user.updated_at %> </td>
        <td></td>
      </tr>
      </tbody>
    </table>

  </section>
</br></br>

<h4>Tasks Assigned</h4>
<%= render partial: 'shared/tasks_table', :locals => { :tasks => @user.tasks_assigned }%>

<h4>Tasks Authored</h4>
<%= render partial: 'shared/tasks_table', :locals => { :tasks => @user.tasks_as_author }%>

</div>